# Propiedades de prueba — BFF
spring.application.name=bff-innovatech-test
ms.proyectos.url=http://localhost:8081
ms.recursos.url=http://localhost:8082
ms.analitica.url=http://localhost:8083
app.rest.connect-timeout=3000
app.rest.read-timeout=5000
